import 'dart:convert';
import 'dart:math';
import 'package:crypto/crypto.dart';
import 'package:danawallet/data/models/bip353_address.dart';
import 'package:danawallet/data/models/name_server_challenge_response.dart';
import 'package:danawallet/data/models/prefix_search_response.dart';
import 'package:danawallet/generated/rust/api/bip39.dart';
import 'package:danawallet/generated/rust/api/structs/network.dart';
import 'package:danawallet/repositories/name_server_repository.dart';
import 'package:danawallet/services/bip353_resolver.dart';
import 'package:logger/logger.dart';

// --- Challenge-auth registration retry matrix (T4b) ------------------------
// Server-side counterpart: dana-nameserver challenge-auth. Verify-before-burn
// (nameserver 72a3917) keeps the nonce valid when only signature verification
// fails, so the same challenge can be re-signed once; any nonce-class
// rejection requires a full re-challenge.
const int _maxReSignRetries = 1;
const int _maxNonceRefreshes = 1;
const List<int> _challenge429BackoffSeconds = [2, 5, 15];
// Server nonce TTL is 300 s; the confirm screen can sit open past it, so
// refresh proactively inside this margin (epoch-seconds comparison).
const int _challengeExpirySafetyMarginSeconds = 10;

/// Server messages that indicate the challenge *signature* failed
/// verification (dana-nameserver challenge-auth src/main.rs verification
/// branch). These do not burn the nonce.
const List<String> _signatureVerificationPhrases = [
  'Signature verification failed',
  'Invalid signature hex',
  'Invalid signature encoding',
  'Signature must be 64 bytes',
];

/// Server messages that indicate the *nonce* itself is spent/stale/foreign
/// (dana-nameserver challenge-auth ERR_EXPIRED / ERR_NO_CHALLENGE /
/// ERR_MISMATCH). These require one fresh challenge.
const List<String> _nonceRejectionPhrases = [
  'Challenge nonce expired',
  'Invalid or missing nonce',
  'Nonce does not match',
];

class DanaAddressService {
  NameServerRepository nameServerRepository;
  final Network network;
  final Random _random = Random.secure();
  String? _domain;

  DanaAddressService({required this.network})
      : nameServerRepository = NameServerRepository(network: network);

  /// Character set for a canonical Dana username label: lowercase ASCII
  /// alphanumeric and hyphens, 1 to 63 characters (mirrors nameserver
  /// `validate_dns_name`, dana-nameserver 61181b1 — README "Validation
  /// Rules" is the contract). Uppercase is rejected, never lowered.
  static final RegExp _danaUsernameLabel = RegExp(r"^[a-z0-9-]{1,63}$");

  /// Validates a Dana username against the nameserver canonical DNS-label
  /// contract (`validate_dns_name` @ dana-nameserver 61181b1):
  /// - `[a-z0-9-]` only, 1-63 characters
  /// - no leading, trailing, or consecutive hyphens
  /// - uppercase is **rejected**, never silently lowercased
  static bool isValidDanaUsername(String name) {
    if (!_danaUsernameLabel.hasMatch(name)) return false;
    if (name.startsWith("-") || name.endsWith("-")) return false;
    if (name.contains("--")) return false;
    return true;
  }

  Future<String> get danaAddressDomain async {
    // lazy initialization of domain
    _domain ??= (await nameServerRepository.getInfo()).domain;

    return _domain!;
  }

  /// Generates a unique ID for requests without external dependencies
  /// Format: timestamp-randomhex (e.g., "1699889234567-a3f2c9d8")
  String _generateUniqueId() {
    final timestamp = DateTime.now().microsecondsSinceEpoch;
    final randomHex =
        _random.nextInt(0xFFFFFFFF).toRadixString(16).padLeft(8, '0');
    return '$timestamp-$randomHex';
  }

  /// Generates a deterministic 3-word alias from entropy using BIP39 wordlist
  /// The alias is generated by using the entropy bytes to select words
  /// [entropy] - The entropy bytes (typically from a SHA-256 hash)
  /// [offset] - Byte offset into the entropy (0, 6, 12, 18, etc.) to use different parts
  static String _generateRandomDanaAddress(
      {required String paymentCode, required int offset}) {
    final entropy = _generateEntropyFromPaymentCode(paymentCode);

    final wordlist = getEnglishWordlist();
    final wordlistSize = wordlist.length;

    // Ensure we have enough bytes for the offset
    if (offset + 6 > entropy.length) {
      // If offset is too large, wrap around using modulo
      offset = offset % (entropy.length - 5);
    }

    // Use different parts of the entropy to select 2 words and 1 number
    // This ensures deterministic selection while avoiding collisions
    final word1Index =
        (entropy[offset] << 8 | entropy[offset + 1]) % wordlistSize;
    final word2Index =
        (entropy[offset + 2] << 8 | entropy[offset + 3]) % wordlistSize;
    final numericValue =
        (entropy[offset + 4] << 8 | entropy[offset + 5]) % 1000;

    return '${wordlist[word1Index]}-${wordlist[word2Index]}-$numericValue';
  }

  /// Generates entropy (SHA-256 hash) from an address
  static List<int> _generateEntropyFromPaymentCode(String paymentCode) {
    final bytes = utf8.encode(paymentCode);
    final hash = sha256.convert(bytes);
    return hash.bytes;
  }

  /// Deterministically generates [count] Dana username candidates from the
  /// payment-code entropy, one per 6-byte window. Candidates that fail
  /// [isValidDanaUsername] are filtered out here, before any availability
  /// probe reaches the network.
  static List<String> generateDanaAddressCandidates({
    required String paymentCode,
    required int count,
  }) {
    final candidates = <String>[];
    for (int attempt = 0; attempt < count; attempt++) {
      final username = _generateRandomDanaAddress(
        paymentCode: paymentCode,
        offset:
            attempt * 6, // Each attempt uses 6 bytes (2 bytes per word/number)
      );
      if (isValidDanaUsername(username)) {
        candidates.add(username);
      } else {
        Logger().w("Dropping invalid generated Dana username candidate: $username");
      }
    }
    return candidates;
  }

  /// Generate an available dana address by trying different username candidates
  /// Returns the first available username found within maxRetries attempts, or null if all are taken
  Future<String?> generateAvailableDanaAddress({
    required String paymentCode,
    required int maxRetries,
  }) async {
    // Candidates failing the nameserver-equivalent validator are dropped
    // BEFORE the isDanaUsernameAvailable probe.
    for (final username in generateDanaAddressCandidates(
        paymentCode: paymentCode, count: maxRetries)) {
      final isAvailable = await isDanaUsernameAvailable(username);
      if (isAvailable) {
        return username;
      }
    }
    return null;
  }

  /// Creates a dana address by calling the external name_server
  ///
  /// [danaAddress] - The address to register.
  /// [requestId] - The unique id for this request, can be useful for tracking requests.
  ///
  /// Returns [DanaAddressCreationResponse] with the created address or error details
  /// [signChallenge] signs the server-issued challenge message with the
  /// wallet-held spend key and returns the 64-byte signature hex. It is a
  /// method parameter only (no field, no global): the service keeps its
  /// `DanaAddressService(network: network)` constructor shape and stays
  /// free of wallet state.
  Future<Bip353Address> registerUser({
    required String username,
    required String paymentCode,
    required Future<String> Function(String message) signChallenge,
  }) async {
    // Reject non-canonical labels locally before ANY network call: the
    // nameserver validates with the same rules (validate_dns_name) and we
    // must not fork a second label by submitting a case variant.
    if (!isValidDanaUsername(username)) {
      throw FormatException(
          "Username must be a lowercase DNS label (1-63 characters of "
          "[a-z0-9-], no leading, trailing or consecutive hyphens): "
          "\"$username\" was rejected");
    }
    final requestId = _generateUniqueId();
    final domain = await danaAddressDomain;
    final Bip353Address danaAddress;

    // We try to resolve the address first to see if it already exists
    try {
      danaAddress = Bip353Address(username: username, domain: domain);
      final resolvedPaymentCode =
          await Bip353Resolver.resolve(danaAddress, network);
      if (resolvedPaymentCode == null) {
        // Address not registered yet, proceed with registration
        Logger().i(
            'Address $username@$domain not found, proceeding with registration');
      } else if (resolvedPaymentCode == paymentCode) {
        // If we find our address, return success there's nothing more to do
        return danaAddress;
      } else if (resolvedPaymentCode != paymentCode) {
        // If we find another address, return error, user must try with a different username
        throw Exception("Dana address already in use");
      }
    } catch (e) {
      // Network or parsing error - we'll let name server try and if it exists it will return an error
      Logger().e('Failed to resolve address for user $username: $e');
      rethrow;
    }

    // Step 2: request the challenge (message + nonce) from the name server.
    var challenge = await _requestChallengeWithBackoff(
      userName: username,
      domain: domain,
      spAddress: paymentCode,
    );

    var reSignsLeft = _maxReSignRetries;
    var nonceRefreshesLeft = _maxNonceRefreshes;

    while (true) {
      // Proactive expiry guard: expiresAt is epoch-seconds (T2 model); the
      // screen can sit open past the 300 s nonce TTL, so re-challenge before
      // burning a signature on a doomed nonce.
      final expiresAt = challenge.expiresAt;
      if (expiresAt != null &&
          DateTime.now().toUtc().millisecondsSinceEpoch ~/ 1000 >=
              expiresAt - _challengeExpirySafetyMarginSeconds) {
        Logger().i('Challenge nonce within expiry margin, re-challenging');
        challenge = await _requestChallengeWithBackoff(
          userName: username,
          domain: domain,
          spAddress: paymentCode,
        );
        continue;
      }

      // Step 3: sign the server message VERBATIM with the wallet-held key.
      final signature = await signChallenge(challenge.message);

      // Step 4: register with nonce + signature.
      try {
        return await nameServerRepository.registerDanaAddress(
          danaAddress: danaAddress,
          paymentCode: paymentCode,
          requestId: requestId,
          nonce: challenge.nonce,
          signature: signature,
        );
      } on RegisterRejectedException catch (e) {
        if (_matchesAny(e.message, _signatureVerificationPhrases) &&
            reSignsLeft > 0) {
          // Verify-before-burn keeps the nonce valid on a pure signature
          // failure: re-sign the SAME message, at most once.
          reSignsLeft--;
          Logger().w(
              'Registration rejected on signature verification, re-signing once: ${e.message}');
          continue;
        }
        if (_matchesAny(e.message, _nonceRejectionPhrases) &&
            nonceRefreshesLeft > 0) {
          // Expired/unknown/mismatched nonce: one fresh challenge + register.
          nonceRefreshesLeft--;
          Logger().w(
              'Registration rejected on nonce, refreshing challenge once: ${e.message}');
          challenge = await _requestChallengeWithBackoff(
            userName: username,
            domain: domain,
            spAddress: paymentCode,
          );
          continue;
        }
        rethrow;
      }
    }
  }

  bool _matchesAny(String message, List<String> phrases) =>
      phrases.any((p) => message.toLowerCase().contains(p.toLowerCase()));

  /// Extracts the server-provided message from a rejected response body
  /// (JSON `message` field when present, raw body otherwise).
  String _serverMessageFromBody(String body) {
    try {
      final decoded = jsonDecode(body);
      if (decoded is Map && decoded['message'] is String) {
        return decoded['message'] as String;
      }
    } catch (_) {
      // Non-JSON body: fall back to the raw text.
    }
    return body;
  }

  /// POST /challenge with the 429 backoff schedule (2 s/5 s/15 s sleeps,
  /// then re-challenge). Any non-429 rejection rethrows untouched; exhaust
  /// of the schedule throws a plain Exception carrying the server message.
  Future<NameServerChallengeResponse> _requestChallengeWithBackoff({
    required String userName,
    required String domain,
    required String spAddress,
  }) async {
    for (var attempt = 0;; attempt++) {
      try {
        return await nameServerRepository.requestChallenge(
          userName: userName,
          domain: domain,
          spAddress: spAddress,
          requestId: _generateUniqueId(),
        );
      } on ChallengeRejectedException catch (e) {
        if (e.status != 429) rethrow;
        if (attempt >= _challenge429BackoffSeconds.length) {
          throw Exception(
              'Challenge request rejected (HTTP 429) after ${_challenge429BackoffSeconds.length} backoff retries: ${_serverMessageFromBody(e.body)}');
        }
        final seconds = _challenge429BackoffSeconds[attempt];
        Logger().w(
            'Challenge 429, backing off ${seconds}s (retry ${attempt + 1}/${_challenge429BackoffSeconds.length})');
        await Future<void>.delayed(Duration(seconds: seconds));
      }
    }
  }

  /// Looks up dana addresses associated with a silent payment address.
  /// Also verifies if the returned Dana address by doing a DNS query
  ///
  /// [paymentCode] - The Silent Payment address to lookup
  ///
  /// Returns the first valid dana address that is found.
  /// Returns a list of dana addresses in the format `user_name@danawallet.app`
  /// Returns an empty list if no addresses are found
  /// Throws an exception for network errors, invalid responses, or malformed data
  Future<Bip353Address?> lookupDanaAddress(String paymentCode) async {
    if (paymentCode.isEmpty) {
      throw ArgumentError("Silent payment address cannot be empty");
    }

    final requestId = _generateUniqueId();
    final addresses =
        await nameServerRepository.lookupDanaAddresses(paymentCode, requestId);

    Logger().i('Found ${addresses.length} dana address(es) for SP address');

    for (var candidate in addresses) {
      if (await Bip353Resolver.verifyPaymentCode(
          candidate, paymentCode, network)) {
        // we just return the first valid candidate
        return candidate;
      } else {
        Logger()
            .w("Name server returned an address that doesn't resolve to ours");
      }
    }
    return null;
  }

  /// Check if a dana address is available for registration
  /// Returns true if the dana address is not taken, false otherwise
  Future<bool> isDanaUsernameAvailable(String username) async {
    try {
      final domain = await danaAddressDomain;
      final parsed = Bip353Address(username: username, domain: domain);
      return await Bip353Resolver.isBip353AddressPresent(parsed, network);
    } catch (e) {
      // If we can't resolve due to network error, assume it's taken to be safe
      Logger().e('Error checking address availability: $e');
      return false;
    }
  }

  /// Searches for dana addresses by prefix
  ///
  /// [prefix] - The prefix to search for (e.g., "alice" to find "alice@domain.com")
  ///
  /// Returns [PrefixSearchResponse] with matching dana addresses
  /// Throws an exception for network errors, invalid responses, or malformed data
  Future<List<Bip353Address>> searchPrefix(String prefix) async {
    if (prefix.isEmpty) {
      throw ArgumentError("Prefix cannot be empty");
    }

    try {
      final requestId = _generateUniqueId();
      final response = await nameServerRepository.searchDanaAddressesWithPrefix(
          prefix, requestId);
      return response.danaAddresses;
    } catch (e) {
      Logger().e('Prefix search request failed for prefix "$prefix": $e');
      throw Exception('Prefix search request failed: $e');
    }
  }
}
